name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11' # Adjust to your Java version
        distribution: 'temurin'

    - name: Download MySQL Connector
      run: |
        wget https://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-java-9.0.0.jar
        mv mysql-connector-java-9.0.0.jar ./src/

    - name: Download JUnit 5 Console Standalone JAR
      run: |
        wget https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.8.2/junit-platform-console-standalone-1.8.2.jar
        mv junit-platform-console-standalone-1.8.2.jar ./src/

    - name: Compile Java Code
      run: |
        javac -cp ./src:./src/mysql-connector-java-9.0.0.jar:./src/junit-platform-console-standalone-1.8.2.jar ./src/LoginApp.java ./src/LoginAppTest.java

    - name: Run JUnit Tests
      run: |
        java -cp ./src:./src/mysql-connector-java-9.0.0.jar:./src/junit-platform-console-standalone-1.8.2.jar org.junit.platform.console.ConsoleLauncher --scan-classpath
