name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download MySQL Connector/J into the src folder
      run: |
        # Download the MySQL connector jar file (version 8.0.26)
        curl -L -o ./src/mysql-connector-java-8.0.26.jar https://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-java-8.0.26.tar.gz
        tar -xvzf ./src/mysql-connector-java-8.0.26.tar.gz -C ./src

    - name: Verify MySQL Connector/J download
      run: |
        # Verify that the file is downloaded and check its content type
        file ./src/mysql-connector-java-8.0.26.jar

    - name: List files (Debugging step)
      run: ls -R ./src

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Compile Java Code
      run: |
        # Use `find` to locate all Java files in `src` and compile them to `bin` folder
        find ./src -name "*.java" > sources.txt
        javac -cp "./src/mysql-connector-java-8.0.26.jar" -d ./bin @sources.txt

    - name: Run Main Class
      run: |
        # If the class is in a package, make sure to specify the fully qualified class name
        java -cp "./bin:./src/mysql-connector-java-8.0.26.jar" LoginAppTest
