name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: List files (Debugging step)
      run: ls -R ./src  # Verify the presence of necessary files

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Download JUnit JAR (JUnit 4.x)
      run: |
        curl -L -o junit-4.13.2.jar https://repo1.maven.org/maven2/junit/junit/4.13.2/junit-4.13.2.jar
        curl -L -o hamcrest-core-1.3.jar https://repo1.maven.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar

    - name: Compile Java Code
      run: |
        # Compile all files, including JUnit and MySQL dependencies
        javac -cp ./src/mysql-connector-j-9.0.0.jar:junit-4.13.2.jar:hamcrest-core-1.3.jar -d ./bin ./src/LoginApp.java ./src/LoginAppTest.java

    - name: Run Tests
      run: |
        # Run the JUnit tests
        java -cp ./bin:./src/mysql-connector-j-9.0.0.jar:junit-4.13.2.jar:hamcrest-core-1.3.jar org.junit.runner.JUnitCore LoginAppTest
