name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: List files (Debugging step)
      run: ls -R ./src  # Verify that the mysql-connector-j-9.0.0.jar is in the src folder

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'



    - name: Run Main Class
      run: |
        # Ensure the classpath includes both the compiled classes and the mysql connector
        java -cp ./src/mysql-connector-j-9.0.0.jar LoginAppTest.java
