name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: List files (Debugging step)
      run: ls -R ./src  # Verify that the mysql-connector-j-9.0.0.jar is in the src folder

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Compile Java Code
      run: |
        # Manually specify the files to compile
        javac -cp ./src/mysql-connector-j-9.0.0.jar -d ./bin ./src/LoginApp.java ./src/LoginAppTest.java  # Add more files if needed

    - name: Run Main Class
      run: |
        # Run the LoginApp class (assuming it's in the default package or the correct package is used)
        java -cp ./bin:./src/mysql-connector-j-9.0.0.jar LoginApp
