name: CI Workflow

on:
  push:
    branches:
      - main  # or master if you are using master as the main branch
  pull_request:
    branches:
      - main  # or master if you are using master as the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download MySQL Connector/J (Direct JAR download)
      run: |
        curl -L -o mysql-connector-java-8.0.28.jar https://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-java-8.0.28.jar

    - name: List files (Debugging step)
      run: ls -R

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adoptium'

    - name: Compile Java Code
      run: |
        javac -cp ./src:./mysql-connector-java-8.0.28.jar -d ./bin ./src/**/*.java

    - name: Run Tests
      run: |
        java -cp ./bin:./mysql-connector-java-8.0.28.jar org.junit.platform.console.ConsoleLauncher --scan-classpath
