name: CI Workflow

on:
  push:
    branches:
      - main  # or master if you are using master as the main branch
  pull_request:
    branches:
      - main  # or master if you are using master as the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download MySQL Connector/J into the src folder
      run: |
        curl -L -o ./src/mysql-connector-java-8.0.28.jar https://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-java-8.0.28.jar

    - name: List files (Debugging step)
      run: ls -R ./src

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'


    - name: Compile Java Code
      run: |
        # Ensure that the source files are compiled correctly
        javac -cp ./src/mysql-connector-java-8.0.28.jar -d ./bin ./src/**/*.java

    - name: Run Main Class
      run: |
        java -cp ./bin:./src/mysql-connector-java-8.0.28.jar LoginAppTest
